# Deploy script to run on each deployment

- hosts: all

  vars:

    service_directory: "/opt/{{ lookup('env', 'service') }}"

    log_directory: "{{ service_directory }}/logs"
    log_archive: "{{ log_directory }}/{{ ansible_date_time.date }}-{{ ansible_date_time.time }}"

    maven_directory: "{{ service_directory }}/maven"

    java_autodeployer_destination: "{{ maven_directory }}/java_autodeployer.jar"
    java_autodeployer_repository_url: "http://nexus.jhc.co.uk/nexus/content/groups/development"
    java_autodeployer_artifact_id: "FigaroJavaDeployer"
    java_autodeployer_group_id: "jhc.util"

    figaroweb_install_config: "{{ service directory}}/figaroweb.install"

  tasks:

    - include: deployment/java_autodeployer.yml

    - include: deployment/archive_logs.yml