# Deploy script to run on each deployment

- hosts: all

  vars:

    service_directory: "/opt/{{ lookup('env', 'service') }}"
    log_directory: "{{ service_directory }}/logs"
    log_archive: "{{ log_directory }}/{{ ansible_date_time.date }}-{{ ansible_date_time.time }}"
    maven_directory: "{{ service_directory }}/maven"

  tasks:

    - include: deployment/java_autodeployer.yml

    - include: deployment/archive_logs.yml