# Deploy script to run on each deployment

- hosts: all

  vars:

    service_directory: "/opt/{{ lookup('env', 'service') }}"
    deploy_playbooks: 
    - deployment/java_autodeployer.yml
    - deployment/archive_logs.yml

  tasks:

    - include: "{{ item }}"
      vars:
        service_directory: "{{ service_directory }}"
      with_items: "{{ deploy_playbooks }}"